name: lrs_app_v3
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dartz: 0.9.0
  freezed_annotation: 0.7.1
  flutter_bloc: 5.0.1
  uuid: 2.0.4
  kt_dart: 0.7.0+1
  injectable: 0.3.0
  get_it: 4.0.2
  auto_route: 0.4.5
  mockito: 4.1.1
  flushbar: 1.10.4
  equatable: 1.2.2
  google_fonts: 1.0.0
  path_provider: 1.6.7
  draggable_scrollbar: 0.0.4
  audioplayers: 0.15.1
  data_connection_checker: 0.3.4
  hive: 1.4.1+1
  firebase_auth: 0.16.0
  cloud_firestore: 0.13.5
  cloud_functions: 0.5.0
  pedantic: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.9.0
  freezed: 0.10.7
  injectable_generator: 0.3.5
  auto_route_generator: 0.4.8
  bloc_test: 6.0.1
  test: 1.14.3
  json_serializable: 3.3.0
  hive_generator: 0.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
