name: lrs_app_v3
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  lrs_data_client:
    git: git@git.hndrk.xyz:lrs-app/data-client.git
  # automatically update versions. Change to static versions for compatibility once more developers work on this project.
  dartz:
  freezed_annotation:
  flutter_bloc:
  uuid:
  kt_dart:
  injectable:
  get_it:
  auto_route:
  mockito:
  flushbar: 1.10.4
  equatable:
  google_fonts:
  path_provider:
  draggable_scrollbar:
  audioplayers:
  data_connection_checker:
  hive:
  firebase_auth:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  injectable_generator:
  auto_route_generator:
  bloc_test:
  test:
  json_serializable:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
