name: lrs_app_v3
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  lrs_data_client:
    git: git@git.hndrk.xyz:lrs-app/data-client.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true